### ISSUE TITLE
Viewing video effects graph file crashes MacBook & reboots OS

### ISSUE THREAD

**Issue by ManjitBedi** [DanMillerDev/ARFoundation_VFX#1]
I am having a serious problem if I try to view the video effects graph file,  it will crash my computer.  Not your problem as such but I have logged the issue with Unity QA & they cannot reproduce it.  The UI will freeze and the after some time a kernel panic happens. 

It happens 100% of the time on my MacBook Pro model from late 2016 using Intel Graphics.  I am using MacOs Catalina 10.15.1 & Unity 2019.3 b10.  And I just updated the package for the video effects graph to 7.1.2.

Any advice would be appreciated. 

[unity 2019.3 crash.txt](https://github.com/DanMillerDev/ARFoundation_VFX/files/3832964/unity.2019.3.crash.txt)

```
panic(cpu 2 caller 0xffffff7f8fac8ad5): userspace watchdog timeout: no successful checkins from com.apple.WindowServer in 140 seconds
service: com.apple.logd, total successful checkins since load (1300 seconds ago): 131, last successful checkin: 0 seconds ago
service: com.apple.WindowServer, total successful checkins since load (1270 seconds ago): 113, last successful checkin: 140 seconds ago
```

**Comment by ManjitBedi** [comment]
After going back & forth with Unity tech support;  I completely deleted Unity & the library files & it works now.  Quite drastic - a file was messed up somewhere?

**Comment by farcaller** [comment]
@ManjitBedi can you note what exactly you deleted? I got the same issue and it drives me nuts.
